=== veteska/jan_veteska/jan_veteska.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="konfigurace_wowka">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nastaveni_grafiky">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="obecne">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="resolution" name="rozliseni"/>
                    <xs:element name="refresh" type="zapVyp"/>
                    <xs:element name="rezim_zobrazeni">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="V okne"/>
                                <xs:enumeration value="Cela obrazovka"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element type="kvalita" name="multisampling"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="efekty_sveta">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="teren_vzdalenost" type="kvalita"/>
                    <xs:element name="teren_textury" type="kvalita"/>
                    <xs:element name="texture_detaily" type="kvalita"/>
                    <xs:element name="pocasi" type="kvalita"/>
                    <xs:element name="vyostrovani" type="zapVyp"/>
                    <xs:element name="level_of_detail" type="zapVyp"/>
                    <xs:element name="anti-aliasing" type="zapVyp"/>
                    <xs:element name="bloom" type="zapVyp"/>
                    <xs:element name="svetelne_paprsky" type="zapVyp"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="stiny">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="teren" type="zapVyp"/>
                    <xs:element name="mrtvy_effect" type="zapVyp"/>
                    <xs:element name="stiny_pocasi" type="zapVyp"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="gamma">
                  <xs:simpleType>
                      <xs:restriction base="xs:integer">
                          <xs:minInclusive value="1"/>
                          <xs:maxInclusive value="17"/>
                      </xs:restriction>
                  </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="uzivatelsky_profil" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="jmeno"/>
              <xs:element type="xs:integer" name="level"/>
              <xs:element name="nastaveni_profilu">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="zvuk">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="celkova_hlasitost" type="procenta"/>
                          <xs:element name="hlasitost_hudby" type="procenta"/>
                          <xs:element name="hlasitost_zvuku" type="procenta"/>
                          <xs:element name="hlasitost_dialogu" type="procenta"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="prevraceni_kamery">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="mys">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="osaX" use="optional" type="zapVyp"/>
                                  <xs:attribute name="osaY" use="optional" type="zapVyp"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="ovladac">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="osaX" use="optional" type="zapVyp"/>
                                  <xs:attribute name="osaY" use="optional" type="zapVyp"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ovladani">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="citlivost_mysi">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="vRozhrani" use="optional" type="citlivost"/>
                                  <xs:attribute name="veHre" use="optional" type="citlivost"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="clickt_to_move" type="zapVyp"/>
                          <xs:element name="auto_clear_AFK" type="zapVyp"/>
                          <xs:element name="block_trades" type="zapVyp"/>
                          <xs:element name="auto_self_cast" type="zapVyp"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="zobrazeni">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="vyukove_zpravy" type="zapVyp"/>
                          <xs:element name="jmena_hracu" type="zapVyp"/>
                          <xs:element name="hracovi_tituly" type="zapVyp"/>
                          <xs:element name="npc_jmena" type="zapVyp"/>
                          <xs:element name="zobrazeni_vlastniho_jmena" type="zapVyp"/>
                          <xs:element name="zobrazeni_helmy" type="zapVyp"/>
                          <xs:element name="zobrazeni_plaste" type="zapVyp"/>
                          <xs:element name="instatnt_quest_text" type="zapVyp"/>
                          <xs:element name="buff_durations" type="zapVyp"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="jazyk">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="titulky" type="zapVyp"/>
                        </xs:sequence>
                        <xs:attribute name="dialogy" use="optional" type="lang"/>
                        <xs:attribute name="texty" use="optional" type="lang"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="rozsirene_moznosti">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="chat" type="zapVyp"/>
                          <xs:element name="zamceni_chatu" type="zapVyp"/>
                          <xs:element name="zobrani_bublin_chatu" type="zapVyp"/>
                          <xs:element name="combat_text">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element  name="dmg" type="zapVyp"/>
                                <xs:element  name="healing" type="zapVyp"/>
                                <xs:element  name="zobrazeni_aury" type="zapVyp"/>
                                <xs:element  name="rozbrazeni_reputace" type="zapVyp"/>
                                <xs:element  name="zobrazeni_praelskeho_healu" type="zapVyp"/>
                                <xs:element  name="honory" type="zapVyp"/>
                                <xs:element  name="rozbrazeni_dodge" type="zapVyp"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="zobrazeni_stavu">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute  name="zivot" use="optional" type="zapVyp"/>
                                  <xs:attribute  name="mana" use="optional" type="zapVyp"/>
                                  <xs:attribute  name="energie" use="optional" type="zapVyp"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element  name="zobrazeni_napovedy" type="zapVyp"/>
                          <xs:element  name="nahled_poskozenychPredmetu" type="zapVyp"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    
      <xs:simpleType name="zapVyp">
          <xs:restriction base="xs:string">
              <xs:enumeration value="Zapnuto"/>
              <xs:enumeration value="Vypnuto"/>
          </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="kvalita">
          <xs:restriction base="xs:string">
              <xs:enumeration value="Nizsi"/>
              <xs:enumeration value="Stredni"/>
              <xs:enumeration value="Vyssi"/>
              <xs:enumeration value="Nejlepsi"/>
          </xs:restriction>
      </xs:simpleType>
	  
	  
	  <xs:simpleType name="resolution">
          <xs:restriction base="xs:string">
              <xs:enumeration value="1920x1080"/>
              <xs:enumeration value="800x600"/>
              <xs:enumeration value="1280x720"/>
              <xs:enumeration value="1040x768"/>
          </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="procenta">
          <xs:restriction base="xs:integer">
              <xs:minInclusive value="0"/>
              <xs:maxInclusive value="100"/>
          </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="citlivost">
          <xs:restriction base="xs:integer">
              <xs:minInclusive value="0"/>
              <xs:maxInclusive value="4"/>
          </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="lang">
          <xs:restriction base="xs:string">
              <xs:enumeration value="Anglictina"/>
              <xs:enumeration value="Cestina"/>
              <xs:enumeration value="Nemcina"/>
              <xs:enumeration value="Rustina"/>
              <xs:enumeration value="Japonstina"/>
              <xs:enumeration value="Elfstina"/>
          </xs:restriction>
      </xs:simpleType>
</xs:schema>

=== veteska/jan_veteska/jan_veteska.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="jan_veteska.xsl"?>

<konfigurace_wowka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jan_veteska.xsd">
    <nastaveni_grafiky>
        <obecne>
            <rozliseni>1920x1080</rozliseni>
            <refresh>Zapnuto</refresh>
            <rezim_zobrazeni>Cela obrazovka</rezim_zobrazeni>
            <multisampling>Nejlepsi</multisampling>
        </obecne>
        <efekty_sveta>
            <teren_vzdalenost>Nejlepsi</teren_vzdalenost>
			<teren_textury>Nejlepsi</teren_textury>
			<texture_detaily>Nejlepsi</texture_detaily>
			<pocasi>Nejlepsi</pocasi>
			<vyostrovani>Zapnuto</vyostrovani>
			<level_of_detail>Zapnuto</level_of_detail>
            <anti-aliasing>Zapnuto</anti-aliasing>
            <bloom>Zapnuto</bloom>
            <svetelne_paprsky>Zapnuto</svetelne_paprsky>			
        </efekty_sveta>
		<stiny>
            <teren>Zapnuto</teren>
            <mrtvy_effect>Zapnuto</mrtvy_effect>
            <stiny_pocasi>Zapnuto</stiny_pocasi>
        </stiny>
		<gamma>9</gamma>            
    </nastaveni_grafiky>
    
    <!--Uzivatelsky profil c.1-->
    <uzivatelsky_profil>
        <jmeno>Honza1</jmeno>
        <level>60</level>
        <nastaveni_profilu>
            <zvuk>
                <celkova_hlasitost>100</celkova_hlasitost>
                <hlasitost_hudby>100</hlasitost_hudby>
                <hlasitost_zvuku>100</hlasitost_zvuku>
                <hlasitost_dialogu>100</hlasitost_dialogu>
            </zvuk>
			<prevraceni_kamery>
                    <mys osaX="Vypnuto" osaY="Vypnuto"/>
                    <ovladac osaX="Vypnuto" osaY="Vypnuto"/>
			</prevraceni_kamery>					
            <ovladani>
                <citlivost_mysi vRozhrani="1" veHre="1"/>
                <clickt_to_move>Zapnuto</clickt_to_move>
				<auto_clear_AFK>Zapnuto</auto_clear_AFK>
				<block_trades>Vypnuto</block_trades>
				<auto_self_cast>Vypnuto</auto_self_cast>
            </ovladani>
            <zobrazeni>
                <vyukove_zpravy>Vypnuto</vyukove_zpravy>
                <jmena_hracu>Vypnuto</jmena_hracu>
                <hracovi_tituly>Vypnuto</hracovi_tituly>
                <npc_jmena>Zapnuto</npc_jmena>
                <zobrazeni_vlastniho_jmena>Zapnuto</zobrazeni_vlastniho_jmena>
                <zobrazeni_helmy>Zapnuto</zobrazeni_helmy>
				<zobrazeni_plaste>Zapnuto</zobrazeni_plaste>
				<instatnt_quest_text>Zapnuto</instatnt_quest_text>
				<buff_durations>Vypnuto</buff_durations>						     
            </zobrazeni>
            <jazyk dialogy="Anglictina" texty="Anglictina">
                <titulky>Zapnuto</titulky>
            </jazyk>
            <rozsirene_moznosti>
                <chat>Zapnuto</chat>
                <zamceni_chatu>Vypnuto</zamceni_chatu>
                <zobrani_bublin_chatu>Zapnuto</zobrani_bublin_chatu>
                <combat_text>
                    <dmg>Zapnuto</dmg>
                    <healing>Zapnuto</healing>
                    <zobrazeni_aury>Zapnuto</zobrazeni_aury>
                    <rozbrazeni_reputace>Zapnuto</rozbrazeni_reputace>
                    <zobrazeni_praelskeho_healu>Zapnuto</zobrazeni_praelskeho_healu>
					<honory>Zapnuto</honory>
					<rozbrazeni_dodge>Vypnuto</rozbrazeni_dodge>
                </combat_text>
                <zobrazeni_stavu zivot="Zapnuto" mana="Zapnuto" energie="Zapnuto" />
                <zobrazeni_napovedy>Vypnuto</zobrazeni_napovedy>
                <nahled_poskozenychPredmetu>Zapnuto</nahled_poskozenychPredmetu>
            </rozsirene_moznosti>
        </nastaveni_profilu>
    </uzivatelsky_profil>
	
	<!--Uzivatelsky profil c2.-->
    <uzivatelsky_profil>
        <jmeno>Kamil</jmeno>
        <level>50</level>
        <nastaveni_profilu>
            <zvuk>
                <celkova_hlasitost>80</celkova_hlasitost>
                <hlasitost_hudby>80</hlasitost_hudby>
                <hlasitost_zvuku>80</hlasitost_zvuku>
                <hlasitost_dialogu>10</hlasitost_dialogu>
            </zvuk>
			<prevraceni_kamery>
                    <mys osaX="Zapnuto" osaY="Zapnuto"/>
                    <ovladac osaX="Vypnuto" osaY="Vypnuto"/>
			</prevraceni_kamery>					
            <ovladani>
                <citlivost_mysi vRozhrani="2" veHre="2"/>
                <clickt_to_move>Vypnuto</clickt_to_move>
				<auto_clear_AFK>Vypnuto</auto_clear_AFK>
				<block_trades>Vypnuto</block_trades>
				<auto_self_cast>Zapnuto</auto_self_cast>
            </ovladani>
            <zobrazeni>
                <vyukove_zpravy>Zapnuto</vyukove_zpravy>
                <jmena_hracu>Vypnuto</jmena_hracu>
                <hracovi_tituly>Zapnuto</hracovi_tituly>
                <npc_jmena>Zapnuto</npc_jmena>
                <zobrazeni_vlastniho_jmena>Vypnuto</zobrazeni_vlastniho_jmena>
                <zobrazeni_helmy>Vypnuto</zobrazeni_helmy>
				<zobrazeni_plaste>Zapnuto</zobrazeni_plaste>
				<instatnt_quest_text>Vypnuto</instatnt_quest_text>
				<buff_durations>Vypnuto</buff_durations>						     
            </zobrazeni>
            <jazyk dialogy="Anglictina" texty="Nemcina">
                <titulky>Zapnuto</titulky>
            </jazyk>
            <rozsirene_moznosti>
                <chat>Zapnuto</chat>
                <zamceni_chatu>Zapnuto</zamceni_chatu>
                <zobrani_bublin_chatu>Vypnuto</zobrani_bublin_chatu>
                <combat_text>
                    <dmg>Zapnuto</dmg>
                    <healing>Vypnuto</healing>
                    <zobrazeni_aury>Vypnuto</zobrazeni_aury>
                    <rozbrazeni_reputace>Zapnuto</rozbrazeni_reputace>
                    <zobrazeni_praelskeho_healu>Zapnuto</zobrazeni_praelskeho_healu>
					<honory>Zapnuto</honory>
					<rozbrazeni_dodge>Zapnuto</rozbrazeni_dodge>
                </combat_text>
                <zobrazeni_stavu zivot="Vypnuto" mana="Zapnuto" energie="Zapnuto" />
                <zobrazeni_napovedy>Vypnuto</zobrazeni_napovedy>
                <nahled_poskozenychPredmetu>Zapnuto</nahled_poskozenychPredmetu>
            </rozsirene_moznosti>
        </nastaveni_profilu>
    </uzivatelsky_profil>
	
	<!--Uzivatelsky profil c.3-->
    <uzivatelsky_profil>
        <jmeno>Kungen</jmeno>
        <level>40</level>
        <nastaveni_profilu>
            <zvuk>
                <celkova_hlasitost>20</celkova_hlasitost>
                <hlasitost_hudby>10</hlasitost_hudby>
                <hlasitost_zvuku>10</hlasitost_zvuku>
                <hlasitost_dialogu>10</hlasitost_dialogu>
            </zvuk>
			<prevraceni_kamery>
                    <mys osaX="Vypnuto" osaY="Vypnuto"/>
                    <ovladac osaX="Vypnuto" osaY="Vypnuto"/>
			</prevraceni_kamery>					
            <ovladani>
                <citlivost_mysi vRozhrani="1" veHre="1"/>
                <clickt_to_move>Vypnuto</clickt_to_move>
				<auto_clear_AFK>Vypnuto</auto_clear_AFK>
				<block_trades>Vypnuto</block_trades>
				<auto_self_cast>Vypnuto</auto_self_cast>
            </ovladani>
            <zobrazeni>
                <vyukove_zpravy>Zapnuto</vyukove_zpravy>
                <jmena_hracu>Zapnuto</jmena_hracu>
                <hracovi_tituly>Zapnuto</hracovi_tituly>
                <npc_jmena>Zapnuto</npc_jmena>
                <zobrazeni_vlastniho_jmena>Zapnuto</zobrazeni_vlastniho_jmena>
                <zobrazeni_helmy>Zapnuto</zobrazeni_helmy>
				<zobrazeni_plaste>Zapnuto</zobrazeni_plaste>
				<instatnt_quest_text>Zapnuto</instatnt_quest_text>
				<buff_durations>Zapnuto</buff_durations>						     
            </zobrazeni>
            <jazyk dialogy="Japonstina" texty="Anglictina">
                <titulky>Zapnuto</titulky>
            </jazyk>
            <rozsirene_moznosti>
                <chat>Zapnuto</chat>
                <zamceni_chatu>Zapnuto</zamceni_chatu>
                <zobrani_bublin_chatu>Zapnuto</zobrani_bublin_chatu>
                <combat_text>
                    <dmg>Zapnuto</dmg>
                    <healing>Zapnuto</healing>
                    <zobrazeni_aury>Zapnuto</zobrazeni_aury>
                    <rozbrazeni_reputace>Zapnuto</rozbrazeni_reputace>
                    <zobrazeni_praelskeho_healu>Zapnuto</zobrazeni_praelskeho_healu>
					<honory>Zapnuto</honory>
					<rozbrazeni_dodge>Zapnuto</rozbrazeni_dodge>
                </combat_text>
                <zobrazeni_stavu zivot="Zapnuto" mana="Zapnuto" energie="Zapnuto" />
                <zobrazeni_napovedy>Zapnuto</zobrazeni_napovedy>
                <nahled_poskozenychPredmetu>Zapnuto</nahled_poskozenychPredmetu>
            </rozsirene_moznosti>
        </nastaveni_profilu>
    </uzivatelsky_profil>
	
	<!--Uzivatelsky profil c.4-->
    <uzivatelsky_profil>
        <jmeno>Hydra</jmeno>
        <level>59</level>
        <nastaveni_profilu>
            <zvuk>
                <celkova_hlasitost>70</celkova_hlasitost>
                <hlasitost_hudby>70</hlasitost_hudby>
                <hlasitost_zvuku>70</hlasitost_zvuku>
                <hlasitost_dialogu>50</hlasitost_dialogu>
            </zvuk>
			<prevraceni_kamery>
                    <mys osaX="Zapnuto" osaY="Zapnuto"/>
                    <ovladac osaX="Zapnuto" osaY="Zapnuto"/>
			</prevraceni_kamery>					
            <ovladani>
                <citlivost_mysi vRozhrani="3" veHre="4"/>
                <clickt_to_move>Vypnuto</clickt_to_move>
				<auto_clear_AFK>Vypnuto</auto_clear_AFK>
				<block_trades>Vypnuto</block_trades>
				<auto_self_cast>Vypnuto</auto_self_cast>
            </ovladani>
            <zobrazeni>
                <vyukove_zpravy>Vypnuto</vyukove_zpravy>
                <jmena_hracu>Vypnuto</jmena_hracu>
                <hracovi_tituly>Vypnuto</hracovi_tituly>
